version: "3.1"

services:
  app:
    build: ./app
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}/app:/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Company
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

